server {
    listen 443 ssl;
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_ciphers ECDHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384:AES256-SHA:DES-CBC3-SHA;
    ssl_certificate /etc/ssl/certs/branch.pem;
}
